# -*- coding: utf-8 -*-
"""

"""

from pandapower.plotting import simple_plot 
from pandapower.plotting import simple_plotly
from pandapower.plotting import pf_res_plotly

def plot_topology(output_setup, net):
    if output_setup['plot']['topology'] == True: 
        if net['bus_geodata'].shape[0] == net['bus'].shape[0]:
            simple_plot(net)
        elif net['bus_geodata'].shape[0] == 0:
            print('\n No coordinates were given, so they are going to be autogenerated')
            simple_plot(net)
        else: 
            print('\n Missmatch in the number of coordinates of the buses')
            print(' Plotting will be abborted')
                        
    return

def plot_interactive(output_setup, net, network_name, scenario_name):
    
    # interactive map
    if output_setup['plot']['interactive network'] == True :
        if net['bus_geodata'].shape[0] != net['bus'].shape[0]:
            print('\n Missmatch in the number of coordinates of the buses')
            print(' Plotting of interactive network will be abborted')
        else:
            try:
                plot = simple_plotly(net)
                plot.write_html(output_setup['output_path']+'_'+network_name+'_'+scenario_name+'_interactive_map.html')
                # print(output_setup['output_path']+'results_'+network_name+'_'+scenario_name+'_interactive_map.html')
            except: 
                print('Error while doing the interactive plotting')
                print('Please change the interactive plotting to False to continue')
                print('Program stops.')
                raise
    # interactive heat map
    if  output_setup['plot']['interactive heat map network'] == True:
        if net['bus_geodata'].shape[0] == net['bus'].shape[0]:
            try:
                plot = pf_res_plotly(net)
                plot.write_html(output_setup['output_path']+'_'+network_name+'_'+scenario_name+'_heat_map.html')
                # print(output_setup['output_path']+'results_'+network_name+'_'+scenario_name+'_heat_map.html')
            except: 
                print('Error while doing the interactive heat map plotting')
                print('Please change the interactive plotting to False to continue')
                print('Program stops.')
                raise 
        elif net['bus_geodata'].shape[0] == 0:
            print('\n No coordinates were given, so they are going to be autogenerated')
            try:
                plot = pf_res_plotly(net)
                plot.write_html(output_setup['output_path']+'_'+network_name+'_'+scenario_name+'_heat_map.html')
                # print(output_setup['output_path']+'results_'+network_name+'_'+scenario_name+'_heat_map.html')
            except: 
                print('Error while doing the interactive heat map plotting')
                print('Please change the interactive plotting to False to continue')
                print('Program stops.')
                raise 
            
        else:
            print('\n Missmatch in the number of coordinates of the buses')
            print(' Plotting will be abborted')
                
    return


